var queriesNS = [ 
{ departureStop: 'swk',
  departureStopName: 'Steenwijk',
  arrivalStop: 'bet|4',
  arrivalStopName: 'Best spoor 4',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rheine|0',
  departureStopName: 'Rheine',
  arrivalStop: 'gdk|1a',
  arrivalStopName: 'Geerdijk spoor 1a',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'uhm',
  departureStopName: 'Uithuizermeeden',
  arrivalStop: 'uto|3',
  arrivalStopName: 'Utrecht Overvecht spoor 3',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'co',
  departureStopName: 'Coevorden',
  arrivalStop: 'vdw|1',
  arrivalStopName: 'Vlaardingen West spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'est|1',
  departureStopName: 'Elst spoor 1',
  arrivalStop: 'ltn|1',
  arrivalStopName: 'Lunteren spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'mrn|0',
  departureStopName: 'Maarn',
  arrivalStop: 'londs',
  arrivalStopName: 'London St.Pancras',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ut|12a',
  departureStopName: 'Utrecht Centraal spoor 12a',
  arrivalStop: 'ddr|2b',
  arrivalStopName: 'Dordrecht spoor 2b',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'hdrz|0',
  departureStopName: 'Den Helder Zuid',
  arrivalStop: 'hk',
  arrivalStopName: 'Heemskerk',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gwd|0',
  departureStopName: 'Wildert',
  arrivalStop: 'hor|2',
  arrivalStopName: 'Hollandsche Rading spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'fn|2',
  departureStopName: 'Franeker spoor 2',
  arrivalStop: 'hwob|0',
  arrivalStopName: 'Wolfsburg',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'sgn',
  departureStopName: 'Schagen',
  arrivalStop: 'apd|0',
  arrivalStopName: 'Apeldoorn',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'wt|2',
  departureStopName: 'Weert spoor 2',
  arrivalStop: 'omn|0',
  arrivalStopName: 'Ommen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'hno|2',
  departureStopName: 'Heino spoor 2',
  arrivalStop: 'gvmw|4',
  arrivalStopName: 'Den Haag Moerwijk spoor 4',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bhdv|0',
  departureStopName: 'Boven-Hardinxveld',
  arrivalStop: 'st|1',
  arrivalStopName: 'Soest spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rtz|4',
  departureStopName: 'Rotterdam Zuid spoor 4',
  arrivalStop: 'neuss|0',
  arrivalStopName: 'Neuss Hbf',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'amr|4',
  departureStopName: 'Alkmaar spoor 4',
  arrivalStop: 'almp|0',
  arrivalStopName: 'Almere Parkwijk',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'wienw',
  departureStopName: 'Wien Westbf',
  arrivalStop: 'rtd|0',
  arrivalStopName: 'Rotterdam Centraal',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'odb|0',
  departureStopName: 'Oudenbosch',
  arrivalStop: 'sdm',
  arrivalStopName: 'Schiedam Centrum',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'wp|5',
  departureStopName: 'Weesp spoor 5',
  arrivalStop: 'berlig|0',
  arrivalStopName: 'Berlin-Gesundbrunnen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gv|3',
  departureStopName: 'Den Haag HS spoor 3',
  arrivalStop: 'kmr|1',
  arrivalStopName: 'Klimmen-Ransdaal spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bf',
  departureStopName: 'Baflo',
  arrivalStop: 'kbw|0',
  arrivalStopName: 'Koog Bloemwijk',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'sptn|3',
  departureStopName: 'Santpoort Noord spoor 3',
  arrivalStop: 'lut|2',
  arrivalStopName: 'Geleen-Lutterade spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ddzd|2',
  departureStopName: 'Dordrecht Zuid spoor 2',
  arrivalStop: 'stolr|0',
  arrivalStopName: 'Stolberg Rathaus',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ampo|0',
  departureStopName: 'Almere Poort',
  arrivalStop: 'aml|3b',
  arrivalStopName: 'Almelo spoor 3b',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rlb|0',
  departureStopName: 'Rotterdam Lombardijen',
  arrivalStop: 'mid|0',
  arrivalStopName: 'Heide',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'nm',
  departureStopName: 'Nijmegen',
  arrivalStop: 'ehai',
  arrivalStopName: 'Eindhoven Airport',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bfbi|0',
  departureStopName: 'Berlin Brandenburg Flughafen',
  arrivalStop: 'rtz|4',
  arrivalStopName: 'Rotterdam Zuid spoor 4',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'dvt|0',
  departureStopName: 'Deventer De Scheg',
  arrivalStop: 'esk',
  arrivalStopName: 'Enschede Kennispark',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ypb',
  departureStopName: 'Den Haag Ypenburg',
  arrivalStop: 'hwob|0',
  arrivalStopName: 'Wolfsburg',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'nmh|2',
  departureStopName: 'Nijmegen Heyendaal spoor 2',
  arrivalStop: 'srn|1',
  arrivalStopName: 'Susteren spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'dln|1',
  departureStopName: 'Dalen spoor 1',
  arrivalStop: 'egh|1',
  arrivalStopName: 'Eygelshoven spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gwd|0',
  departureStopName: 'Wildert',
  arrivalStop: 'hamh|0',
  arrivalStopName: 'Hamburg Hbf',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'koben',
  departureStopName: 'K›benhavn Hovedb.',
  arrivalStop: 'dl|0',
  arrivalStopName: 'Dalfsen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'almm|1',
  departureStopName: 'Almere Muziekwijk spoor 1',
  arrivalStop: 'gdg|2',
  arrivalStopName: 'Gouda Goverwelle spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ehst',
  departureStopName: 'Eindhoven Stadion',
  arrivalStop: 'rsn|0',
  arrivalStopName: 'Rijssen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'sgl|1',
  departureStopName: 'Houthem-St Gerlach spoor 1',
  arrivalStop: 'nkk|2',
  arrivalStopName: 'Nijkerk spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'utl',
  departureStopName: 'Utrecht Lunetten',
  arrivalStop: 'wz',
  arrivalStopName: 'Wezep',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'brauns|0',
  departureStopName: 'Braunschweig Hbf',
  arrivalStop: 'zell',
  arrivalStopName: 'Zell am See',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'twl',
  departureStopName: 'Twello',
  arrivalStop: 'btl|3',
  arrivalStopName: 'Boxtel spoor 3',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'eenp|0',
  departureStopName: 'Ennepetal (Gevelsberg)',
  arrivalStop: 'krd',
  arrivalStopName: 'Kerkrade Centrum',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bfbi',
  departureStopName: 'Berlin Brandenburg Flughafen',
  arrivalStop: 'ht|1',
  arrivalStopName: 'Hertogenbosch (\'s) spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gk|1',
  departureStopName: 'Grijpskerk spoor 1',
  arrivalStop: 'zvb',
  arrivalStopName: 'Zevenbergen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gvc|0',
  departureStopName: 'Den Haag Centraal',
  arrivalStop: 'atn|2',
  arrivalStopName: 'Aalten spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'tbu|2',
  departureStopName: 'Tilburg Universiteit spoor 2',
  arrivalStop: 'btl|2',
  arrivalStopName: 'Boxtel spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'wh|1',
  departureStopName: 'Wijhe spoor 1',
  arrivalStop: 'utg|0',
  arrivalStopName: 'Uitgeest',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'harw|0',
  departureStopName: 'Harwich International',
  arrivalStop: 'kmr|2',
  arrivalStopName: 'Klimmen-Ransdaal spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ut|7b',
  departureStopName: 'Utrecht Centraal spoor 7b',
  arrivalStop: 'vndc|1',
  arrivalStopName: 'Veenendaal Centrum spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'edo|0',
  departureStopName: 'Dortmund Hbf',
  arrivalStop: 'atn|2',
  arrivalStopName: 'Aalten spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'kufst',
  departureStopName: 'Kufstein',
  arrivalStop: 'amf',
  arrivalStopName: 'Amersfoort',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ssh|0',
  departureStopName: 'Sassenheim',
  arrivalStop: 'hrt',
  arrivalStopName: 'Horst-Sevenum',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'em',
  departureStopName: 'Emmerich',
  arrivalStop: 'ah|6b',
  arrivalStopName: 'Arnhem spoor 6b',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'hrlk|0',
  departureStopName: 'Heerlen De Kissel',
  arrivalStop: 'flk|0',
  arrivalStopName: 'Lokeren',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ehb|1',
  departureStopName: 'Eindhoven Beukenlaan spoor 1',
  arrivalStop: 'ekz|2',
  arrivalStopName: 'Enkhuizen spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'xpsu',
  departureStopName: 'Szczecin Gumience',
  arrivalStop: 'rtd|14',
  arrivalStopName: 'Rotterdam Centraal spoor 14',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'dmp',
  departureStopName: 'Driemanspolder',
  arrivalStop: 'innsb|0',
  arrivalStopName: 'Innsbruck Hbf',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'kmw',
  departureStopName: 'Koudum-Molkwerum',
  arrivalStop: 'stm',
  arrivalStopName: 'Stedum',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bdpb',
  departureStopName: 'Breda-Prinsenbeek',
  arrivalStop: 'vss|1',
  arrivalStopName: 'Vlissingen Souburg spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'mt|5b',
  departureStopName: 'Maastricht spoor 5b',
  arrivalStop: 'zl|15',
  arrivalStopName: 'Zwolle spoor 15',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'hvs|2',
  departureStopName: 'Hilversum spoor 2',
  arrivalStop: 'rvs|2',
  arrivalStopName: 'Ravenstein spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'utl',
  departureStopName: 'Utrecht Lunetten',
  arrivalStop: 'vdl',
  arrivalStopName: 'Voerendaal',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ahbf',
  departureStopName: 'Aachen Hbf',
  arrivalStop: 'www',
  arrivalStopName: 'Winterswijk West',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'hlm|8',
  departureStopName: 'Haarlem spoor 8',
  arrivalStop: 'almm',
  arrivalStopName: 'Almere Muziekwijk',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'tbg|2',
  departureStopName: 'Terborg spoor 2',
  arrivalStop: 'dwe',
  arrivalStopName: 'De Westereen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'vsv|1',
  departureStopName: 'Varsseveld spoor 1',
  arrivalStop: 'hld|0',
  arrivalStopName: 'Hoek van Holland Haven',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rtst|4b',
  departureStopName: 'Rotterdam Stadion spoor 4b',
  arrivalStop: 'ebok',
  arrivalStopName: 'Bork (Westf)',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gdm|3a',
  departureStopName: 'Geldermalsen spoor 3a',
  arrivalStop: 'vijfsl|0',
  arrivalStopName: 'Vijfsluizen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'stola|0',
  departureStopName: 'Stolberg Altstadt',
  arrivalStop: 'fnzd|0',
  arrivalStopName: 'Antwerpen-Zuid',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'utg',
  departureStopName: 'Uitgeest',
  arrivalStop: 'drh|2',
  arrivalStopName: 'Driehuis spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'vs|0',
  departureStopName: 'Vlissingen',
  arrivalStop: 'da|0',
  arrivalStopName: 'Daarlerveen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'utt|4',
  departureStopName: 'Utrecht Terwijde spoor 4',
  arrivalStop: 'wh|1',
  arrivalStopName: 'Wijhe spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gvc|10',
  departureStopName: 'Den Haag Centraal spoor 10',
  arrivalStop: 'wupph',
  arrivalStopName: 'Wuppertal Hbf',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'zvt|1',
  departureStopName: 'Zandvoort aan Zee spoor 1',
  arrivalStop: 'sdt|0',
  arrivalStopName: 'Sliedrecht',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'lc|1',
  departureStopName: 'Lochem spoor 1',
  arrivalStop: 'ktr',
  arrivalStopName: 'Kesteren',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rl|2',
  departureStopName: 'Ruurlo spoor 2',
  arrivalStop: 'thun|0',
  arrivalStopName: 'Thun',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ww',
  departureStopName: 'Winterswijk',
  arrivalStop: 'rat|2',
  arrivalStopName: 'Raalte spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'dmp|0',
  departureStopName: 'Driemanspolder',
  arrivalStop: 'stjohp|0',
  arrivalStopName: 'St. Johann im Pongau',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bsmz|1',
  departureStopName: 'Bussum Zuid spoor 1',
  arrivalStop: 'amr|3',
  arrivalStopName: 'Alkmaar spoor 3',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bdm|1',
  departureStopName: 'Bedum spoor 1',
  arrivalStop: 'amrn|2',
  arrivalStopName: 'Alkmaar Noord spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ck|0',
  departureStopName: 'Cuijk',
  arrivalStop: 'ust',
  arrivalStopName: 'Usquert',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'oberh',
  departureStopName: 'Oberhausen Hbf',
  arrivalStop: 'ost|0',
  arrivalStopName: 'Olst',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'sk|1',
  departureStopName: 'Sneek spoor 1',
  arrivalStop: 'hlm|3',
  arrivalStopName: 'Haarlem spoor 3',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'mmu|0',
  departureStopName: 'Murnau',
  arrivalStop: 'ro|0',
  arrivalStopName: 'Offenburg',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ksb',
  departureStopName: 'Siegburg',
  arrivalStop: 'amf|5a',
  arrivalStopName: 'Amersfoort spoor 5a',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'lg|3',
  departureStopName: 'Landgraaf spoor 3',
  arrivalStop: 'bkl|3',
  arrivalStopName: 'Breukelen spoor 3',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'tg',
  departureStopName: 'Tegelen',
  arrivalStop: 'assp|1',
  arrivalStopName: 'Amsterdam Science Park spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rzepin',
  departureStopName: 'Rzepin',
  arrivalStop: 'rhn|0',
  arrivalStopName: 'Rhenen',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bl|0',
  departureStopName: 'Beilen',
  arrivalStop: 'ddzd|2',
  arrivalStopName: 'Dordrecht Zuid spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'edkd',
  departureStopName: 'Dortmund-Kirchderne',
  arrivalStop: 'bhg',
  arrivalStopName: 'Bentheim Grens',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'rtd|11',
  departureStopName: 'Rotterdam Centraal spoor 11',
  arrivalStop: 'apn|0',
  arrivalStopName: 'Alphen a/d Rijn',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'na|0',
  departureStopName: 'Nieuw Amsterdam',
  arrivalStop: 'stm|0',
  arrivalStopName: 'Stedum',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'jenbac|0',
  departureStopName: 'Jenbach',
  arrivalStop: 'rlb|2',
  arrivalStopName: 'Rotterdam Lombardijen spoor 2',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'bde|1',
  departureStopName: 'Bunde spoor 1',
  arrivalStop: 'zh',
  arrivalStopName: 'Zuidhorn',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'gd|5b',
  departureStopName: 'Gouda spoor 5b',
  arrivalStop: 'odens|0',
  arrivalStopName: 'Odense',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'lgl',
  departureStopName: 'Glons',
  arrivalStop: 'utl|1',
  arrivalStopName: 'Utrecht Lunetten spoor 1',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'vp|1',
  departureStopName: 'Velp spoor 1',
  arrivalStop: 'ahz',
  arrivalStopName: 'Arnhem Zuid',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'uhm|2',
  departureStopName: 'Uithuizermeeden spoor 2',
  arrivalStop: 'mt|5b',
  arrivalStopName: 'Maastricht spoor 5b',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'lni|0',
  departureStopName: 'Niel',
  arrivalStop: 'utlr|4',
  arrivalStopName: 'Utrecht Leidsche Rijn spoor 4',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'kbd|2',
  departureStopName: 'Krabbendijke spoor 2',
  arrivalStop: 'fffm',
  arrivalStopName: 'Frankfurt (M) Hbf',
  departureTime: '2015-10-05T08:00' }
,
{ departureStop: 'ijt|1',
  departureStopName: 'IJlst spoor 1',
  arrivalStop: 'mrn|1',
  arrivalStopName: 'Maarn spoor 1',
  departureTime: '2015-10-05T08:00' }
];
